# -*- coding: utf-8 -*-
from PyQt5.QtCore import Qt
# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#

#
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QGraphicsView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Настройка основного окна
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(757, 455)

        # Центральный виджет
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # -------------------------------
        # Графическая область (QGraphicsView)
        # -------------------------------
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 421, 401))
        self.graphicsView.setObjectName("graphicsView")

        # -------------------------------
        # Виджет вкладок (QTabWidget)
        # -------------------------------
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(436, 9, 311, 201))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")

        # -------------------------------
        # Первая вкладка: Настройки рисования
        # -------------------------------
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 291, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        # Компоновка чекбоксов
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        # Чекбоксы
        self.checkBox_showCopter = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_showCopter.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox_showCopter)

        self.checkBox_showDistance = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_showDistance.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_showDistance)

        self.checkBox_Warning = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_Warning.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_Warning)

        self.checkBox_stopInZone = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_stopInZone.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_stopInZone)

        self.checkBox_showRestrictedZone = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_showRestrictedZone.setObjectName("checkBox_5")
        self.verticalLayout.addWidget(self.checkBox_showRestrictedZone)

        # Добавление вкладки
        self.tabWidget.addTab(self.tab, "")

        # -------------------------------
        # Вторая вкладка: Управление миссиями
        # -------------------------------
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        # Кнопки управления
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 291, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # Кнопка: Установить/изменить запретную зону
        self.toolButton_setRestrictedZone = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image_folder/red_flag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_setRestrictedZone.setIcon(icon)
        self.toolButton_setRestrictedZone.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_setRestrictedZone.setObjectName("toolButton_2")
        self.verticalLayout_2.addWidget(self.toolButton_setRestrictedZone)

        # Кнопка: Установить маршрут для коптера
        self.toolButton_setRoute = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image_folder/copter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_setRoute.setIcon(icon1)
        self.toolButton_setRoute.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_setRoute.setObjectName("toolButton")
        self.verticalLayout_2.addWidget(self.toolButton_setRoute)

        # Добавление вкладки
        self.tabWidget.addTab(self.tab_2, "")

        # -------------------------------
        # Третья вкладка: Логи
        # -------------------------------
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")

        # Чекбоксы для настроек логирования
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 291, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.checkBox_droneMoves = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_droneMoves.setObjectName("checkBox_6")
        self.verticalLayout_3.addWidget(self.checkBox_droneMoves)

        self.checkBox_alarmsTriggers = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_alarmsTriggers.setObjectName("checkBox_7")
        self.verticalLayout_3.addWidget(self.checkBox_alarmsTriggers)

        self.checkBox_operatorActions = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_operatorActions.setObjectName("checkBox_8")
        self.verticalLayout_3.addWidget(self.checkBox_operatorActions)

        self.checkBox_goalMessages = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_goalMessages.setObjectName("checkBox_9")
        self.verticalLayout_3.addWidget(self.checkBox_goalMessages)

        # Добавление вкладки
        self.tabWidget.addTab(self.tab_3, "")

        # -------------------------------
        # Поле для логов
        # -------------------------------
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(440, 230, 301, 181))
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")

        # Метка над логами
        self.label_logs = QtWidgets.QLabel(self.centralwidget)
        self.label_logs.setGeometry(QtCore.QRect(450, 206, 291, 20))
        self.label_logs.setObjectName("label")

        # Установка центрального виджета
        MainWindow.setCentralWidget(self.centralwidget)

        # -------------------------------
        # Меню и статусная строка
        # -------------------------------
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 757, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # -------------------------------
        # Перевод текста интерфейса
        # -------------------------------
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        # Установка текста для виджетов
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Drone Management"))
        self.checkBox_showCopter.setText(_translate("MainWindow", "Show Сopter"))
        self.checkBox_showDistance.setText(_translate("MainWindow", "Show Distance to Nearest Restricted Zone"))
        self.checkBox_Warning.setText(_translate("MainWindow", "Warning When Approaching a Danger Zone"))
        self.checkBox_stopInZone.setText(_translate("MainWindow", "Stop When Entering a Restricted Zone"))
        self.checkBox_showRestrictedZone.setText(_translate("MainWindow", "Show Restricted Zone"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Draw Settings"))
        self.toolButton_setRestrictedZone.setText(_translate("MainWindow", "Set/Change Restracted Zone"))
        self.toolButton_setRoute.setText(_translate("MainWindow", "Set Route for the Copter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Mission Control"))
        self.checkBox_droneMoves.setText(_translate("MainWindow", "Drone Moves"))
        self.checkBox_alarmsTriggers.setText(_translate("MainWindow", "Alarms and Triggers"))
        self.checkBox_operatorActions.setText(_translate("MainWindow", "Operator actions"))
        self.checkBox_goalMessages.setText(_translate("MainWindow", "Additional Messages on Achieving Required Goals"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Logs"))
        self.label_logs.setText(_translate("MainWindow", "Logs"))


